version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
      MYSQL_DATABASE: ma_base_de_donnees
    networks:
      - clusterswarm
    volumes:
      - clusterswarm_data:/var/lib/mysql
    deploy:
      replicas: 1

  web:
    image: clusterswarm:latest
    labels:
      - "traefik.swarm.network=publicswarm"
      - "traefik.enable=true"
      - "traefik.http.routers.clusterswarm.rule=Host(`clusterswarm.localhost`)"
      - "traefik.http.services.clusterswarm.loadbalancer.server.port=80"
    networks:
      - publicswarm
      - clusterswarm
    depends_on:
      - db
      - redis
    deploy:
      replicas: 5

  redis:
    image: redis:latest
    networks:
      - clusterswarm
    volumes:
      - redis_data:/data
    deploy:
      replicas: 2 

volumes:
  clusterswarm_data:
    driver: local
  redis_data:
    driver: local

networks:
  publicswarm:
    external: true
  clusterswarm:
    external: true
