version: '3.8'

services:
  # Traefik (point d'entrée)
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.swarm=true"
      - "--providers.swarm.network=publicswarm"
      - "--entrypoints.web.address=:80"
      - "--providers.file.filename=/etc/traefik/middlewares.yml"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./middlewares.yml:/etc/traefik/middlewares.yml"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - publicswarm

networks:
  publicswarm:
    external: true
