version: '3.8'

services:
  # Service Web (PHP + Apache) pour Fortune Images
  fortune:
    image: fortune:latest
    networks:
      - publicswarm
    deploy:
      replicas: 1
      labels:
        - "traefik.swarm.network=publicswarm"
        - "traefik.enable=true"
        - "traefik.http.routers.fortune.rule=Host(`fortune.localhost`)"
        - "traefik.http.services.fortune.loadbalancer.server.port=80"
        - "traefik.http.routers.fortune.middlewares=auth@file"

networks:
  publicswarm:
    external: true
