version: '3.8'

services:
  # Service Web (PHP + Apache) pour Fortune Images
  fortune:
    build: ./fortune
    image: fortune:latest
    labels:
      - "traefik.swarm.network=publicswarm"
      - "traefik.enable=true"
      - "traefik.http.routers.fortune.rule=Host(`fortune.localhost`)"
      - "traefik.http.services.fortune.loadbalancer.server.port=80"
    container_name: fortune-images
    networks:
      - publicswarm
    deploy:
      replicas: 1

networks:
  publicswarm:
    external: true
