version: '3.8'

services:
  redis:
    image: redis:latest
    volumes:
      - dataredis:/data
    networks:
      - flask
    deploy:
      replicas: 1

  web:
    image: flask:latest
    volumes:
      - .:/file
    environment:
      - FLASK_ENV=development
    networks:
      - publicswarm
      - flask
    deploy:
      replicas: 1
      labels:
        - "traefik.swarm.network=publicswarm"
        - "traefik.enable=true"
        - "traefik.http.routers.flask.rule=Host(`flask.localhost`)"
        - "traefik.http.services.flask.loadbalancer.server.port=80"
        - "traefik.http.routers.flask.middlewares=auth@file"

networks:
  publicswarm:
    external: true
  flask:
    external: true

volumes:
  dataredis:
    driver: local
