version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    volumes:
      - dataredis:/data
    environment:
      REDIS_ARGS: "--save 10 1"
    networks:
      - publicswarm
    deploy:
      replicas: 1

  site:
    image: mon_flask:latest
    volumes:
      - .:/file
    environment:
      - FLASK_ENV=development
    networks:
      - publicswarm
    deploy:
      replicas: 1
    labels:
      - "traefik.swarm.network=publicswarm"
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`flask.localhost`)"
      - "traefik.http.services.flask.loadbalancer.server.port=80"

networks:
  publicswarm:
    external: true

volumes:
  dataredis:
    driver: local
