version: '3.8'

services:
  apache:
    image: apache:latest
    networks:
      - publicswarm
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=PathPrefix(`/apache`)"
      - "traefik.http.services.apache.loadbalancer.server.port=80"
      - "traefik.http.middlewares.apache-stripprefix.stripprefix.prefixes=/apache"
      - "traefik.http.routers.apache.middlewares=apache-stripprefix"

networks:
  publicswarm:
    external: true
