version: '3.8'

services:
  # Service MySQL
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
      MYSQL_DATABASE: ma_base_de_donnees
    networks:
      - utilisateurs
    volumes:
      - utilisateurs_data:/var/lib/mysql
    deploy:
      replicas: 1

  # Service Web (PHP + Apache)
  web:
    image: utilisateurs:latest
    networks:
      - publicswarm
      - utilisateurs
    depends_on:
      - db
      - redis
    deploy:
      replicas: 3  # Réparti sur 3 nœuds pour le load-balancing
      labels:
          - "traefik.swarm.network=publicswarm"
          - "traefik.enable=true"
          - "traefik.http.routers.utilisateurs.rule=Host(`utilisateurs.localhost`)"
          - "traefik.http.services.utilisateurs.loadbalancer.server.port=80"
          - "traefik.http.routers.utilisateurs.middlewares=auth@file"

  # Service Redis
  redis:
    image: redis:latest
    networks:
      - utilisateurs
    ports:
      - "6379:6379"
    deploy:
      replicas: 1

volumes:
  utilisateurs_data:
    driver: local

networks:
  publicswarm:
    external: true
  utilisateurs:
    external: true
