version: '3.8'

services:
  # Service MySQL
  db:
    image: p4179-167:5000/mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
      MYSQL_DATABASE: ma_base_de_donnees
    networks:
      - publicswarm
    volumes:
      - utilisateurs_data:/var/lib/mysql
    deploy:
      replicas: 1

  # Service Web (PHP + Apache)
  web:
    build: ./utilisateurs  # Utilise le Dockerfile pour construire l'image
    image: mon-serveur-web:latest
    labels:
        - "traefik.swarm.network=publicswarm"
        - "traefik.enable=true"
        - "traefik.http.routers.utilisateurs.rule=Host(`utilisateurs.localhost`)"
        - "traefik.http.services.utilisateurs.loadbalancer.server.port=80"
    container_name: mon-serveur-web
    networks:
      - publicswarm
    depends_on:
      - db
      - redis
    deploy:
      replicas: 3  # Réparti sur 3 nœuds pour le load-balancing

  # Service Redis
  redis:
    image: p4179-167:5000/redis
    container_name: redis
    networks:
      - publicswarm
    ports:
      - "6379:6379"
    deploy:
      replicas: 1

volumes:
  utilisateurs_data:
    driver: local

networks:
  publicswarm:
    external: true
